server:
  port: ${PORT:9015}

logging:
  level:
    org.atmosphere: debug
    
# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,de.mohadipe

spring:
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    # Open-in-view is only needed if you use lazy-loaded entities in your Flow views.
    open-in-view: false
    # Initialize the JPA Entity Manager before considering data.sql so that the EM can create the schema and data.sql contain data
    # defer-datasource-initialization: true
    generate-dll: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: mysql-root-pass
      url: jdbc:mysql://localhost:3306/wertpapiere?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
secondary:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql-root-pass
    url: jdbc:mysql://localhost:3306/verbrauch?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true